BARCLAYS/Controllers/AdministrationController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BARCLAYS.Models;

namespace BARCLAYS.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministrationController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        //
        // GET: /Administration/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Analytics()
        {
            return View();
        }

        #region Masters
        public ActionResult Currency()
        {
            return View();
        }
        #region clients
        public ActionResult Clients()
        {
            return View();
        }
        #endregion       

        public ActionResult BillUnit()
        {
            return View();
        }
        public ActionResult BillCode()
        {
            return View();
        }
        public ActionResult Employee()
        {
            return View();
        }

        public ActionResult Client()
        {
            return View();
        }
        #endregion

        //
        // GET: /Administration/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Administration/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Administration/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Administration/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Administration/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Administration/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Administration/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BARCLAYS/Controllers/AnalyticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BARCLAYS.Controllers
{
    public class AnalyticsController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

    }
}

BARCLAYS/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;

namespace BARCLAYS.Controllers
{
    public class DashboardController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

    }
}

BARCLAYS/Views/Administration/ClientCards.cshtml
@model BARCLAYS.Models.ClientView

@{
    ViewBag.Title = "Contacts Cards";
    ViewBag.ExtraClasses = "fixed-sidebar fixed-navbar";
}

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i class="fa fa-arrow-up"></i>
                </div>
            </a>

            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
                    <li class="active">
                        <span><a href="@Url.Action("Contacts", "Administration")">Contact List</a></span>
                    </li>
                    <li>
                        <span>Contact Cards</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Contact
            </h2>
            <small>Many panels design give you many possibilities.</small>
        </div>
    </div>
</div>

<div class="content animate-panel">
    <div class="row">
        <span class="pull-right"><a class="btn btn-primary" href="@Url.Action("NewClient", "Administration")"><i class="fa fa-plus"></i>&nbsp;New Contact</a></span>
    </div>
    
    <div class="row">
        @foreach (var i in Model.Contact)
        {
            <div class="col-lg-3">
                <div class="hpanel hyellow contact-panel">
                    <div class="panel-body">
                        <img alt="logo" class="img-circle m-b" src="~/Images/a4.jpg">
                        <h3><a href=""> @i.FullName </a></h3>
                        <div class="text-muted font-bold m-b-xs">California, LA</div>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan.
                        </p>
                    </div>
                    <div class="panel-footer contact-footer">
                        <div class="row">
                            <div class="col-md-4 border-right"> <div class="contact-stat"><span>Projects: </span> <strong>200</strong></div> </div>
                            <div class="col-md-4 border-right"> <div class="contact-stat"><span>Messages: </span> <strong>300</strong></div> </div>
                            <div class="col-md-4"> <div class="contact-stat"><span>Views: </span> <strong>400</strong></div> </div>
                        </div>
                    </div>
                </div>
            </div>
        }
        
    </div>
</div>

BARCLAYS/Views/Administration/Clients.cshtml
@{
    ViewBag.Title = "BARCLAYS Dashboard";
    ViewBag.ExtraClasses = "fixed-sidebar fixed-navbar";
}

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i class="fa fa-arrow-up"></i>
                </div>
            </a>

            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
                    <li class="active">
                        <span>Contact List</span>
                    </li>
                    <li>
                        <span><a href="@Url.Action("ContactCards", "Administration")">Contact Cards</a></span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Contact
            </h2>
            <small>Many panels design give you many possibilities.</small>
        </div>
    </div>
</div>

<div class="content animate-panel">

    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-heading">
                    <div class="panel-tools">
                        @*<a class="btn btn-primary"><i class="fa fa-plus"></i></a>*@
                        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        <a class="closebox"><i class="fa fa-times"></i></a>
                    </div>
                    <i class="fa fa-user"></i>&nbsp;Contact List
                </div>
                <div class="panel-body">
                    <span class="pull-right"><a class="btn btn-primary" href="@Url.Action("NewClient", "Administration")"><i class="fa fa-plus"></i>&nbsp;New Contact</a></span>
                    <table class="table table-bordered table-striped" width="100%" id="datatable-ajax" data-url="/Administration/GetClients/">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Type</th>                               
                                <th>Contact Code</th>
                                <th>Status</th>
                                <th>Date Created</th>
                                <th>Last Update</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table> 
                </div>
                <div class="panel-footer">
                    This is standard panel footer
                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/datatables/js")
    @Scripts.Render("~/bundles/datatablesBootstrap/js")
    @Scripts.Render("~/bundles/datatablesPlugins/js")
    <script src="~/Scripts/Administration/Contacts.js"></script>
}

BARCLAYS/Views/Administration/Index.cshtml
@{
    ViewBag.Title = "BARCLAYS Dashboard";
    ViewBag.ExtraClasses = "fixed-sidebar fixed-navbar hide-sidebar";
}

<div class="content animate-panel">
    <div class="row">
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6">
            <div class="hpanel">
                <div class="panel-body text-center">
                    <i class="fa fa-shopping-cart fa-4x"></i>

                    @*<h1 class="m-xs">$1 206,90</h1>*@

                    <h5 class="font-extra-bold no-margins text-success">
                        Shop
                    </h5>
                    @*<small>Lorem ipsum dolor sit amet, consectetur adipiscing elit vestibulum.</small>*@
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6">
            <div class="hpanel">
                <div class="panel-body text-center">
                    <i class="fa fa-folder fa-4x"></i>

                    @*<h1 class="m-xs">$1 206,90</h1>*@

                    <h5 class="font-extra-bold no-margins text-success">
                        Packages
                    </h5>
                    @*<small>Lorem ipsum dolor sit amet, consectetur adipiscing elit vestibulum.</small>*@
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6">
            <div class="hpanel">
                <div class="panel-body text-center">
                    <i class="fa fa-bullhorn fa-4x"></i>

                    @*<h1 class="m-xs">$1 206,90</h1>*@

                    <h5 class="font-extra-bold no-margins text-success">
                        Feedback
                    </h5>
                    @*<small>Lorem ipsum dolor sit amet, consectetur adipiscing elit vestibulum.</small>*@
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6">
            <div class="hpanel">
                <div class="panel-body text-center">
                    <i class="fa fa-comments-o fa-4x"></i>

                    @*<h1 class="m-xs">$1 206,90</h1>*@

                    <h5 class="font-extra-bold no-margins text-success">
                        BARCLAYS Rep
                    </h5>
                    @*<small>Lorem ipsum dolor sit amet, consectetur adipiscing elit vestibulum.</small>*@
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6">
            <div class="hpanel">
                <div class="panel-body text-center">
                    <i class="fa fa-ticket fa-4x"></i>

                    @*<h1 class="m-xs">$1 206,90</h1>*@

                    <h5 class="font-extra-bold no-margins text-success">
                        Tickets
                    </h5>
                    @*<small>Lorem ipsum dolor sit amet, consectetur adipiscing elit vestibulum.</small>*@
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6">
            <div class="hpanel">
                <div class="panel-body text-center">
                    <i class="fa fa-comment fa-4x"></i>

                    @*<h1 class="m-xs">$1 206,90</h1>*@

                    <h5 class="font-extra-bold no-margins text-success">
                        SMS
                    </h5>
                    @*<small>Lorem ipsum dolor sit amet, consectetur adipiscing elit vestibulum.</small>*@
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6">
            <div class="hpanel">
                <div class="panel-body text-center">
                    <i class="fa fa-music fa-4x"></i>

                    @*<h1 class="m-xs">$1 206,90</h1>*@

                    <h5 class="font-extra-bold no-margins text-success">
                        CBRT Tunes
                    </h5>
                    @*<small>Lorem ipsum dolor sit amet, consectetur adipiscing elit vestibulum.</small>*@
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6">
            <div class="hpanel">
                <div class="panel-body text-center">
                    <i class="fa fa-money fa-4x"></i>

                    @*<h1 class="m-xs">$1 206,90</h1>*@

                    <h5 class="font-extra-bold no-margins text-success">
                        Invoices
                    </h5>
                    @*<small>Lorem ipsum dolor sit amet, consectetur adipiscing elit vestibulum.</small>*@
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6">
            <div class="hpanel">
                <div class="panel-body text-center">
                    <i class="fa fa-user fa-4x"></i>

                    @*<h1 class="m-xs">$1 206,90</h1>*@

                    <h5 class="font-extra-bold no-margins text-success">
                        My Account
                    </h5>
                    @*<small>Lorem ipsum dolor sit amet, consectetur adipiscing elit vestibulum.</small>*@
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/flot/js")

    <script type="text/javascript">

            $(function () {

                /**
                 * Flot charts data and options
                 */
                var data1 = [ [0, 55], [1, 48], [2, 40], [3, 36], [4, 40], [5, 60], [6, 50], [7, 51] ];
                var data2 = [ [0, 56], [1, 49], [2, 41], [3, 38], [4, 46], [5, 67], [6, 57], [7, 59] ];

                var chartUsersOptions = {
                    series: {
                        splines: {
                            show: true,
                            tension: 0.4,
                            lineWidth: 1,
                            fill: 0.4
                        },
                    },
                    grid: {
                        tickColor: "#f0f0f0",
                        borderWidth: 1,
                        borderColor: 'f0f0f0',
                        color: '#6a6c6f'
                    },
                    colors: [ "#de2275", "#efefef"],
                };

                $.plot($("#flot-line-chart"), [data1, data2], chartUsersOptions);

                /**
                 * Flot charts 2 data and options
                 */
                var chartIncomeData = [
                    {
                        label: "line",
                        data: [ [1, 10], [2, 26], [3, 16], [4, 36], [5, 32], [6, 51] ]
                    }
                ];

                var chartIncomeOptions = {
                    series: {
                        lines: {
                            show: true,
                            lineWidth: 0,
                            fill: true,
                            fillColor: "#64cc34"

                        }
                    },
                    colors: ["#de2275"],
                    grid: {
                        show: false
                    },
                    legend: {
                        show: false
                    }
                };

                $.plot($("#flot-income-chart"), chartIncomeData, chartIncomeOptions);


        });
    </script>
}

BARCLAYS/Views/Administration/NewClient.cshtml
@model  BARCLAYS.Models.ClientView

@{
    ViewBag.Title = "BARCLAYS Dashboard";
    ViewBag.ExtraClasses = "fixed-sidebar fixed-navbar";
}

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i class="fa fa-arrow-up"></i>
                </div>
            </a>

            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
                    <li class="active">
                        <span><a href="@Url.Action("Clients", "Administration")">Contact List</a></span>
                    </li>
                    <li>
                        <span><a href="@Url.Action("ClientCards", "Administration")">Contact Cards</a></span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Contact
            </h2>
            <small>Many panels design give you many possibilities.</small>
        </div>
    </div>
</div>

<div class="content animate-panel">

    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-heading">
                    <div class="panel-tools">
                        @*<a class="btn btn-primary"><i class="fa fa-plus"></i></a>*@
                        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        <a class="closebox"><i class="fa fa-times"></i></a>
                    </div>
                    <i class="fa fa-user"></i>&nbsp;New Contact
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" action="@Url.Action("AddAClient","Administration")" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Contact Type</label>
                            <div class="col-sm-10">
                                <fieldset>
                                    @foreach (var i in Model.ClientType)
                                    {
                                        <div class="radio radio-primary radio-inline">
                                            <input type="radio" id="radio_@i.Id" value="@i.Id" data-attr="@i.Type" name="radioInline" class="ctype">
                                            <label for="inlineRadio1"> @i.Type </label>
                                        </div>
                                    }
                                </fieldset>                      
                             </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label personal">First Name</label>
                            <div class="col-sm-4"><input class="form-control personal" type="text" name="FirstName"></div>
                            <label class="col-sm-2 control-label corperate">Company Name</label>
                            <div class="col-sm-4"><input class="form-control corperate" type="text" name="CompanyName"></div>
                        </div> 
                        <div class="form-group">
                            <label class="col-sm-2 control-label personal">Last Name</label>
                            <div class="col-sm-4"><input class="form-control personal" type="text" name="LastName"></div>
                            <label class="col-sm-2 control-label corperate">Comp. Fax</label>
                            <div class="col-sm-4"><input class="form-control corperate" type="text" name="CompanyFax"></div>
                        </div>  
                        <div class="form-group">
                            <label class="col-sm-2 control-label personal">Email</label>
                            <div class="col-sm-4"><input class="form-control personal" type="text" name="Email"></div>
                            <label class="col-sm-2 control-label corperate">Company Email</label>
                            <div class="col-sm-4"><input class="form-control corperate" type="text" name="CompanyEmail"></div>
                        </div> 
                        <div class="form-group">
                            <label class="col-sm-2 control-label personal">Address</label>
                            <div class="col-sm-4"><input class="form-control personal" type="text" name="Address"></div>
                            <label class="col-sm-2 control-label corperate">Company Address</label>
                            <div class="col-sm-4"><input class="form-control corperate" type="text" name="CompanyAddress"></div>
                        </div>  
                        <div class="form-group">
                            <label class="col-sm-2 control-label personal">Phone Number</label>
                            <div class="col-sm-4"><input class="form-control personal" type="text" name="PhoneNumber"></div>
                            <label class="col-sm-2 control-label corperate">Company Phone</label>
                            <div class="col-sm-4"><input class="form-control corperate" type="text" name="CompanyPhone"></div>
                        </div>  
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Mobile Number</label>
                            <div class="col-sm-4"><input class="form-control personal" type="text" name="MobileNumber"></div>
                            <label class="col-sm-2 control-label">VAT</label>
                            <div class="col-sm-4"><input class="form-control corperate" type="text" name="CompanyVAT"></div>
                        </div> 
                        <div class="form-group">
                            <label class="col-sm-2 control-label personal">DOB</label>
                            <div class="col-sm-4"><input id="dob" type="text" value="02-16-2012" class="form-control datapicker personal" name="DOB"></div>
                            <label class="col-sm-2 control-label corperate">Date of Incorp.</label>
                            <div class="col-sm-4"><input id="dateOfIncorp" type="text" value="02-16-2012" class="form-control datapicker corperate" name="CompanyDateStarted"></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label personal">NID</label>
                            <div class="col-sm-4"><input class="form-control personal" type="text" name="NIDNumber"></div>
                            <label class="col-sm-2 control-label corperate">Company Reg. Number</label>
                            <div class="col-sm-4"><input class="form-control corperate" type="text" name="CompanyRegistrationNumber"></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Passport Number</label>
                            <div class="col-sm-4"><input class="form-control personal" type="text" name="PassportNumber"></div>
                            <label class="col-sm-2 control-label">BRN</label>
                            <div class="col-sm-4"><input class="form-control" type="text" name="CompanyBRN"></div>
                        </div>  
                        <div class="form-group">
                            @*<label class="col-sm-2 control-label">Next Of Kin</label>
                            <div class="col-sm-4"><input class="form-control personal" type="text" name="NextOFKin"></div>*@
                            <label class="col-sm-2 control-label">Company Website</label>
                            <div class="col-sm-4"><input class="form-control corperate" type="text" name="CompanyWebsite" value="http://"></div>
                        </div>  
                                         
                        @*<div class="form-group">
                            <label class="col-sm-2 control-label">Help text</label>
                            <div class="col-sm-10">
                                <input class="form-control" type="text"> <span class="help-block m-b-none">A block of help text that breaks onto a new line and may extend beyond one line.</span>
                            </div>
                        </div>*@                       
                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Upload</label>
                            <div class="col-sm-10"><input type="file" name="files"></div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-8 col-sm-offset-2">
                                <button class="btn btn-danger" type="button" onclick="window.location.href='@Url.Action("Contacts","Administration")'"><i class="fa fa-times-circle"></i>&nbsp;Cancel</button>
                                <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i>&nbsp;Save changes</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    This is standard panel footer
                </div>
            </div>
        </div>
    </div>

</div>

@section Styles {
    @Styles.Render("~/bundles/xeditable/css")
    @Styles.Render("~/bundles/select2/css")
    @Styles.Render("~/bundles/touchspin/css")
    @Styles.Render("~/bundles/datepicker/css")
    @Styles.Render("~/bundles/bootstrapCheckbox/css")
    @Styles.Render("~/bundles/datetimepicker/css")
    @Styles.Render("~/bundles/clockpicker/css")

    <link href="~/Scripts/New Filer/jquery.fileuploader.css" media="all" rel="stylesheet">
    <link href="~/Scripts/New Filer/css/jquery.fileuploader-theme-thumbnails.css" media="all" rel="stylesheet">
}

@section Scripts {
    @Scripts.Render("~/bundles/datatables/js")
    @Scripts.Render("~/bundles/datatablesBootstrap/js")
    @Scripts.Render("~/bundles/datatablesPlugins/js")
    @Scripts.Render("~/bundles/moment/js")
    @Scripts.Render("~/bundles/xeditable/js")
    @Scripts.Render("~/bundles/select2/js")
    @Scripts.Render("~/bundles/touchspin/js")
    @Scripts.Render("~/bundles/datepicker/js")
    @Scripts.Render("~/bundles/datetimepicker/js")
    @Scripts.Render("~/bundles/clockpicker/js")
    <script src="~/Scripts/New Filer/jquery.fileuploader.min.js"></script>
    <script src="~/Scripts/New Filer/js/custom.js"></script>
    <script src="~/Scripts/Administration/Contacts.js"></script>
}