BARCLAYS/Controllers/AnalyticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BARCLAYS.Controllers
{
    public class AnalyticsController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

    }
}

BARCLAYS/Controllers/AppViewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BARCLAYS.Controllers
{
    public class AppViewsController : Controller
    {

        public ActionResult Contacts()
        {
            return View();
        }

        public ActionResult Projects()
        {
            return View();
        }

        public ActionResult SocialBoard()
        {
            return View();
        }

        public ActionResult Timeline()
        {
            return View();
        }

        public ActionResult ProfilePage()
        {
            return View();
        }

        public ActionResult Blog()
        {
            return View();
        }

        public ActionResult BlogArticle()
        {
            return View();
        }

        public ActionResult Forum()
        {
            return View();
        }

        public ActionResult ForumDetails()
        {
            return View();
        }

        public ActionResult Calendar()
        {
            return View();
        }

        public ActionResult ProjectDetail()
        {
            return View();
        }

        public ActionResult Mailbox()
        {
            return View();
        }

        public ActionResult Gallery()
        {
            return View();
        }

        public ActionResult FileManager()
        {
            return View();
        }

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult Invoice()
        {
            return View();
        }

        public ActionResult ChatView()
        {
            return View();
        }

        public ActionResult AppPlans()
        {
            return View();
        }

        public ActionResult Faq()
        {
            return View();
        }

        public ActionResult Notes()
        {
            return View();
        }

        public ActionResult EmailCompose()
        {
            return View();
        }

        public ActionResult EmailView()
        {
            return View();
        }


    }
}

BARCLAYS/Controllers/ChartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BARCLAYS.Controllers
{
    public class ChartsController : Controller
    {

        public ActionResult ChartJs()
        {
            return View();
        }

        public ActionResult FlotCharts()
        {
            return View();
        }

        public ActionResult InlineGraphs()
        {
            return View();
        }

        public ActionResult Chartist()
        {
            return View();
        }

        public ActionResult C3Charts()
        {
            return View();
        }

    }
}

BARCLAYS/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;

namespace BARCLAYS.Controllers
{
    public class DashboardController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

    }
}

BARCLAYS/Views/Shared/_Footer.cshtml
<footer class="footer">
    <span class="pull-right">
        Example text
    </span>
    Company 2015-2020
</footer>

BARCLAYS/Views/Shared/_Header.cshtml
<div class="color-line">
</div>
<div id="logo" class="light-version">
    @*<span>
        EMIT
    </span>*@
    <span>
        BARCLAYS ONLINE
    </span>
    @*<img src="~/Content/img/logo.svg" width="100%" height="45px" alt="BARCLAYS" />*@
</div>
<nav role="navigation">
    @*<div class="header-link hide-menu"><i class="fa fa-bars"></i></div>*@
    <div class="small-logo">
        <span class="text-primary">BARCLAYS APP</span>
    </div>
    <form role="search" class="navbar-form-custom" method="post" action="#">
        <div class="form-group">
            <input type="text" placeholder="Search something special" class="form-control" name="search">
        </div>
    </form>
    <div class="mobile-menu">
        <button type="button" class="navbar-toggle mobile-menu-toggle" data-toggle="collapse" data-target="#mobile-collapse">
            <i class="fa fa-chevron-down"></i>
        </button>
        <div class="collapse mobile-navbar" id="mobile-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a class="" href="@Url.Action("Login", "CommonViews")">Login</a>
                </li>
                <li>
                    <a class="" href="@Url.Action("Register", "CommonViews")">Logout</a>
                </li>
                <li>
                    <a class="" href="@Url.Action("ProfilePage", "AppViews")">Profile</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="navbar-right">
        <ul class="nav navbar-nav no-borders">
            <li class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="pe-7s-speaker"></i>
                </a>
                <ul class="dropdown-menu hdropdown notification animated flipInX">
                    <li>
                        <a>
                            <span class="label label-success">NEW</span> It is a long established.
                        </a>
                    </li>
                    <li>
                        <a>
                            <span class="label label-warning">WAR</span> There are many variations.
                        </a>
                    </li>
                    <li>
                        <a>
                            <span class="label label-danger">ERR</span> Contrary to popular belief.
                        </a>
                    </li>
                    <li class="summary"><a href="#">See all notifications</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="pe-7s-keypad"></i>
                </a>
                <div class="dropdown-menu hdropdown bigmenu animated flipInX">
                    <table>
                        <tbody>
                            <tr>
                                <td>
                                    <a href="@Url.Action("Projects", "AppViews")">
                                        <i class="pe pe-7s-portfolio text-info"></i>
                                        <h5>Projects</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("Mailbox", "AppViews")">
                                        <i class="pe pe-7s-mail text-warning"></i>
                                        <h5>Email</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("Contacts", "AppViews")">
                                        <i class="pe pe-7s-users text-success"></i>
                                        <h5>Contacts</h5>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <a href="@Url.Action("Forum", "AppViews")">
                                        <i class="pe pe-7s-comment text-info"></i>
                                        <h5>Forum</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("Index", "Analytics")">
                                        <i class="pe pe-7s-graph1 text-danger"></i>
                                        <h5>Analytics</h5>
                                    </a>
                                </td>
                                <td>
                                    <a href="@Url.Action("FileManager", "AppViews")">
                                        <i class="pe pe-7s-box1 text-success"></i>
                                        <h5>Files</h5>
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle label-menu-corner" href="#" data-toggle="dropdown">
                    <i class="pe-7s-mail"></i>
                    <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu hdropdown animated flipInX">
                    <div class="title">
                        You have 4 new messages
                    </div>
                    <li>
                        <a>
                            It is a long established.
                        </a>
                    </li>
                    <li>
                        <a>
                            There are many variations.
                        </a>
                    </li>
                    <li>
                        <a>
                            Lorem Ipsum is simply dummy.
                        </a>
                    </li>
                    <li>
                        <a>
                            Contrary to popular belief.
                        </a>
                    </li>
                    <li class="summary"><a href="#">See All Messages</a></li>
                </ul>
            </li>
            <li>
                <a href="#" id="sidebar" class="right-sidebar-toggle">
                    <i class="pe-7s-upload pe-7s-news-paper"></i>
                </a>
            </li>
            <li class="dropdown">
                <a href="login.html">
                    <i class="pe-7s-upload pe-rotate-90"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

BARCLAYS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>BARCLAYS | @ViewBag.Title</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Primary vendor style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
                                              
    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="@Html.PageClass() @ViewBag.ExtraClasses">

    <!-- Simple splash screen-->
    <div class="splash">
        <div class="color-line"></div>
        <div class="splash-title">
            <img src="~/Content/img/ui-topfm.png" alt="BARCLAYS" />
            <h1>BARCLAYS - Online</h1>
            <p>Created by Infini Tech. </p>
            <div class="spinner">
                <div class="rect1">
                </div>
                <div class="rect2">
                </div>
                <div class="rect3">
                </div>
                <div class="rect4">
                </div>
                <div class="rect5">
                </div>
            </div>
        </div>
    </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header -->
    <div id="header">
        @Html.Partial("_Header")
    </div>

    <!-- Navigation -->
    @*<aside id="menu">
        @Html.Partial("_Navigation")
    </aside>*@

    <!-- Main view  -->
    <div id="wrapper">
        @RenderBody()

        <!-- Right Sidebar -->
        @Html.Partial("_Right_Sidebar")

        <!-- Footer-->
        @Html.Partial("_Footer")
    </div>

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/homer/js")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

BARCLAYS/Views/Shared/_Layout_Blank.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>BARCLAYS | @ViewBag.Title</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Primary HOMER style -->
    @Styles.Render("~/bundles/font-awesome/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/peicon7stroke/css")
    @Styles.Render("~/bundles/homer/css")
</head>
<body class="blank">

    <!-- Simple splash screen-->
    <div class="splash">
        <div class="color-line"></div>
        <div class="splash-title">
            <img src="~/Content/img/ui-topfm.png" alt="BARCLAYS" />
            <h1>BARCLAYS - Online</h1>
            <p>Created by Infini Tech. </p>
            <div class="spinner"> 
                <div class="rect1">
                </div>
                <div class="rect2">
                </div> 
                <div class="rect3">
                </div> 
                <div class="rect4">
                </div>
                <div class="rect5">
                </div> 
            </div> 
        </div> 
    </div>
    <!--[if lt IE 7]>
    <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <div class="color-line"></div>

    <div class="back-link">
        <a href="https://www.mu.barclaysafrica.com/personal/transactional-accounts/explore/" target="_blank" class="btn btn-BARCLAYS-deep"><i class="fa fa-home"></i>&nbsp;BARCLAYS Home</a>
    </div>

    <!-- Main view  -->
    @RenderBody()

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/homer/js")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)

</body>
</html>

BARCLAYS/Views/Shared/_Navigation.cshtml
@using BARCLAYS.Models;
@using BARCLAYS.Controllers;
@using System.Globalization;

@{ 
    AdministrationController ac = new AdministrationController();
    ApplicationDbContext db = new ApplicationDbContext();

    string fn, ln, ffn = "";
    string roles = "";
    if (User.Identity.IsAuthenticated)
    {
        BARCLAYS.Models.Utilities lu = new BARCLAYS.Models.Utilities();
        fn = lu.GetUser(User)?.FirstName;
        ln = lu.GetUser(User)?.LastName;
        ffn = $"{fn} {ln}";

        var allRoles = db.Roles.ToList();
        lu.GetUser(User).Roles.ToList().ForEach(r =>
        {
            roles += allRoles.Where(rr => rr.Id == r.RoleId).FirstOrDefault().Name + ", ";
        });
    }
    else
    {

    }
}

<div id="navigation">
    <div class="profile-picture">
        <a href="@Url.Action("Index", "Dashboard")">
            <img src="~/Images/profile.jpg" class="img-circle m-b" alt="logo">
        </a>

        <div class="stats-label text-color">
            <span class="font-extra-bold font-uppercase">@ffn</span>

            <div class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <small class="text-muted">@roles <b class="caret"></b></small>
                </a>
                <ul class="dropdown-menu animated fadeInRight m-t-xs">
                    <li><a href="contacts.html">Contacts</a></li>
                    <li><a href="profile.html">Profile</a></li>
                    <li><a href="analytics.html">Analytics</a></li>
                    <li class="divider"></li>
                    <li><a href="login.html">Logout</a></li>
                </ul>
            </div>
            <div id="sparkline1" class="small-chart m-t-sm"></div>
            <div>
                <h4 class="font-extra-bold m-b-xs">
                    $260 104,200
                </h4>
                <small class="text-muted">Your income from the last year in sales product X.</small>
            </div>
        </div>
    </div>

    <ul class="nav metismenu" id="side-menu">
        <li class="@Html.IsSelected(controller: "Administration")">
            <a href="#"><span class="nav-label"><i class="fa fa-dashboard"></i>&nbsp;Dashboard</span><span class="fa arrow"></span> </a>
            <ul class="nav nav-second-level">
                <li class="@Html.IsSelected(action: "Index")"><a href="@Url.Action("Index", "Administration")"><i class="fa fa-dashboard"></i>&nbsp;Dashboard</a></li>
                <li class="@Html.IsSelected(action: "Analytics")"><a href="@Url.Action("Analytics", "Administration")"><i class="fa fa-line-chart"></i>&nbsp;Analytics</a></li>
            </ul>
        </li>
        <li class="@Html.IsSelected(controller: "Administration")">
            <a href="#"><span class="nav-label"><i class="fa fa-list-ul"></i>&nbsp;Masters</span><span class="fa arrow"></span> </a>
            <ul class="nav nav-second-level">
                <li class="@Html.IsSelected(action: "Clients")">
                    <a href="#"><span class="nav-label"><i class="fa fa-user"></i>&nbsp;Clients</span><span class="fa arrow"></span> </a>
                    <ul class="nav nav-second-level">
                        <li class="@Html.IsSelected(action: "Index")"><a href="@Url.Action("ClientSectors", "Administration")"><i class="fa fa-group"></i>&nbsp;Sectors</a></li>
                        <li class="@Html.IsSelected(action: "Analytics")"><a href="@Url.Action("ClientCategory", "Administration")"><i class="fa fa-group"></i>&nbsp;Category</a></li>
                        <li class="@Html.IsSelected(action: "Analytics")"><a href="@Url.Action("Clients", "Administration")"><i class="fa fa-user"></i>&nbsp;Clients</a></li>
                    </ul>
                </li>
                <li class="@Html.IsSelected(action: "BillUnit")"><a href="@Url.Action("Agents", "Administration")"><i class="fa fa-user"></i>&nbsp;Agents</a></li>
                <li class="@Html.IsSelected(action: "BillCode")"><a href="@Url.Action("Users", "Administration")"><i class="fa fa-user"></i>&nbsp;Users</a></li>
                <li class="@Html.IsSelected(action: "BillCode")"><a href="@Url.Action("Users", "Administration")"><i class="fa fa-money"></i>&nbsp;Rate Cards</a></li>
                <li class="@Html.IsSelected(action: "Assets")">
                    <a href="#"><span class="nav-label"><i class="fa fa-car"></i>&nbsp;Assets</span><span class="fa arrow"></span> </a>
                    <ul class="nav nav-second-level">
                        <li class="@Html.IsSelected(action: "Analytics")"><a href="@Url.Action("Clients", "Administration")"><i class="fa fa-user"></i>&nbsp;Assets</a></li>
                    </ul>
                </li>
                <li class="@Html.IsSelected(action: "Assets")">
                    <a href="#"><span class="nav-label"><i class="fa fa-clock-o"></i>&nbsp;Spots</span><span class="fa arrow"></span> </a>
                    <ul class="nav nav-second-level">
                        <li class="@Html.IsSelected(action: "Analytics")"><a href="@Url.Action("ClientCategory", "Administration")"><i class="fa fa-group"></i>&nbsp;Spot Length</a></li>
                    </ul>
                </li>
                <li class="@Html.IsSelected(action: "Components")">
                    <a href="#"><span class="nav-label"><i class="fa fa-user"></i>&nbsp;Users</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li class="@Html.IsSelected(action: "ChartJs")"><a href="@Url.Action("ChartJs", "Charts")"><i class="fa fa-users"></i>&nbsp;Department</a></li>
                        <li class="@Html.IsSelected(action: "FlotCharts")"><a href="@Url.Action("FlotCharts", "Charts")"><i class="fa fa-users"></i>&nbsp;Groups</a></li>
                        <li class="@Html.IsSelected(action: "InlineGraphs")"><a href="@Url.Action("InlineGraphs", "Charts")"><i class="fa fa-user"></i>&nbsp;Employees</a></li>
                    </ul>
                </li>
                <li class="@Html.IsSelected(action: "Components")">
                    <a href="#"><span class="nav-label"><i class="fa fa-user"></i>&nbsp;Client</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li class="@Html.IsSelected(action: "FlotCharts")"><a href="@Url.Action("FlotCharts", "Charts")"><i class="fa fa-users"></i>&nbsp;Groups</a></li>
                        <li class="@Html.IsSelected(action: "InlineGraphs")"><a href="@Url.Action("InlineGraphs", "Charts")"><i class="fa fa-user"></i>&nbsp;Clients</a></li>
                    </ul>
                </li>

                <li class="@Html.IsSelected(action: "Alerts")"><a href="@Url.Action("Alerts", "Interface")"><i class="fa fa-money"></i>&nbsp;Expense Types</a></li>
                <li class="@Html.IsSelected(action: "Modals")"><a href="@Url.Action("Modals", "Interface")"><i class="fa fa-file-word-o"></i>&nbsp;Proposals</a></li>
                <li class="@Html.IsSelected(action: "LoadingButtons")"><a href="@Url.Action("LoadingButtons", "Interface")"><i class="fa fa-file-word-o"></i>&nbsp;Contracts</a></li>
                <li class="@Html.IsSelected(action: "DraggablePanels")"><a href="@Url.Action("DraggablePanels", "Interface")"><i class="fa fa-money"></i>&nbsp;Leave Types</a></li>
                <li class="@Html.IsSelected(action: "CodeEditor")"><a href="@Url.Action("CodeEditor", "Interface")"><i class="fa fa-exclamation"></i>&nbsp;Priority Types</a></li>
                <li class="@Html.IsSelected(action: "EmailTemplate")"><a href="@Url.Action("EmailTemplate", "Interface")"><i class="fa fa-calendar-times-o"></i>&nbsp;Meeting/Minutes</a></li>
            </ul>
        </li>
        <li class="@Html.IsSelected(controller: "AppViews")">
            <a href="#"><span class="nav-label"><i class="fa fa-briefcase"></i>&nbsp;Projects</span><span class="fa arrow"></span> </a>
            <ul class="nav nav-second-level">
                <li class="@Html.IsSelected(action: "Projects")"><a href="@Url.Action("Projects", "AppViews")"><i class="fa fa-briefcase"></i>&nbsp;Projects</a></li>
                <li class="@Html.IsSelected(action: "Contacts")"><a href="@Url.Action("Contacts", "AppViews")"><i class="fa fa-tasks"></i>&nbsp;Tasks</a></li>
            </ul>
        </li>
        <li class="@Html.IsSelected(controller: "AppViews")">
            <a href="#"><span class="nav-label"><i class="fa fa-tasks"></i>&nbsp;Tasks</span><span class="fa arrow"></span> </a>
            <ul class="nav nav-second-level">
                <li class="@Html.IsSelected(action: "Contacts")"><a href="@Url.Action("Contacts", "AppViews")"><i class="fa fa-tasks"></i>&nbsp;Tasks</a></li>
            </ul>
        </li>
        <li class="@Html.IsSelected(controller: "AppViews")">
            <a href="#"><span class="nav-label"><i class="fa fa-tasks"></i>&nbsp;Reports</span><span class="fa arrow"></span> </a>
            <ul class="nav nav-second-level">
                <li class="@Html.IsSelected(action: "Contacts")"><a href="@Url.Action("Contacts", "AppViews")"><i class="fa fa-user"></i>&nbsp;Employee</a></li>
                <li class="@Html.IsSelected(action: "Contacts")"><a href="@Url.Action("Contacts", "AppViews")"><i class="fa fa-user"></i>&nbsp;Employee Usage</a></li>
                <li class="@Html.IsSelected(action: "Contacts")"><a href="@Url.Action("Contacts", "AppViews")"><i class="fa fa-user"></i>&nbsp;Client</a></li>
                <li class="@Html.IsSelected(action: "Contacts")"><a href="@Url.Action("Contacts", "AppViews")"><i class="fa fa-file-o"></i>&nbsp;Invoice</a></li>
            </ul>
        </li>
        <li class="@Html.IsSelected(controller: "AppViews")">
            <a href="#"><span class="nav-label"><i class="fa fa-calendar"></i>&nbsp;Timesheet</span><span class="fa arrow"></span> </a>
            <ul class="nav nav-second-level">
                <li class="@Html.IsSelected(controller: "Widgets")">
                    <a href="@Url.Action("Index", "Widgets")"> <span class="nav-label"><i class="fa fa-calendar"></i>&nbsp;Calendar Entry</span></a>
                </li>
                <li class="@Html.IsSelected(controller: "Widgets")">
                    <a href="@Url.Action("Index", "Widgets")"> <span class="nav-label"><i class="fa fa-clock-o"></i>&nbsp;Timer</span></a>
                </li>
                <li class="@Html.IsSelected(action: "Contacts")"><a href="@Url.Action("Contacts", "AppViews")"><i class="fa fa-table"></i>&nbsp;Spreadsheet</a></li>
            </ul>
        </li>
        <li class="@Html.IsSelected(controller: "AppViews")">
            <a href="#"><span class="nav-label"><i class="fa fa-cogs"></i>&nbsp;Settings</span><span class="fa arrow"></span> </a>
            <ul class="nav nav-second-level">
                <li class="@Html.IsSelected(action: "Components")">
                    <a href="#"><span class="nav-label"><i class="fa fa-wrench"></i>&nbsp;Configurations</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li class="@Html.IsSelected(action: "ChartJs")"><a href="@Url.Action("ChartJs", "Charts")"><i class="fa fa-building"></i>&nbsp;Company Details</a></li>
                        <li class="@Html.IsSelected(action: "FlotCharts")"><a href="@Url.Action("FlotCharts", "Charts")"><i class="fa fa-cog"></i>&nbsp;Global Settings</a></li>
                        <li class="@Html.IsSelected(action: "InlineGraphs")"><a href="@Url.Action("InlineGraphs", "Charts")"><i class="fa fa-money"></i>&nbsp;Currency</a></li>
                        <li class="@Html.IsSelected(action: "InlineGraphs")"><a href="@Url.Action("InlineGraphs", "Charts")"><i class="fa fa-money"></i>&nbsp;Approval Process</a></li>
                    </ul>
                </li>
                <li class="@Html.IsSelected(action: "Components")">
                    <a href="#"><span class="nav-label"><i class="fa fa-cog"></i>&nbsp;Settings</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li class="@Html.IsSelected(action: "FlotCharts")"><a href="@Url.Action("FlotCharts", "Charts")"><i class="fa fa-exclamation-circle"></i>&nbsp;Logs</a></li>
                        <li class="@Html.IsSelected(action: "FlotCharts")"><a href="@Url.Action("FlotCharts", "Charts")"><i class="fa fa-exclamation-triangle"></i>&nbsp;Audits</a></li>
                        <li class="@Html.IsSelected(action: "InlineGraphs")"><a href="@Url.Action("InlineGraphs", "Charts")"><i class="fa fa-user"></i>&nbsp;Exceptions</a></li>
                    </ul>
                </li>
                <li class="@Html.IsSelected(action: "Contacts")"><a href="@Url.Action("Contacts", "AppViews")"><i class="fa fa-question-circle"></i>&nbsp;Help</a></li>
            </ul>
        </li>
    </ul>
</div>